### ISSUE TITLE
Encountering difficulties in retrieving data from a public API.

### ISSUE THREAD

**Issue by ayush362** [ayush362/random-activity-generator#1]
I was trying to create a random activity generator using a public API.. 
But I am not able to fetch the data using the API..
@sangeet
Path : sections/Mainsection.jsx

**Comment by sangeet** [comment]
This is a problem from the API side as the API is giving us CORS error.
I believe this might be a problem just with the localhost, but either way, it's not a problem on our end but rather their's.

I could not find any instructions regarding this API on what API headers to attach to not have such problem, so there's not much we can do as there's no documentation. Please let me know if there's any documentation for this API which contains information about what API headers to send.

I have also added a small code review for Mainsection.jsx. Please find it at https://github.com/ayush362/random-activity-generator/pull/2
